#:kivy 1.1.0


FloatLayout:
    BoxLayout:
        padding: 10
        pos_hint: {'right': 1, 'top': 1}
        size_hint: (None, None)
        size: (100, 50)
        Button:
            text: 'Settings'
            on_press: app.show_settings()

    BoxLayout:
        padding: 10
        pos_hint: {'left': 1, 'top': 1}
        size_hint: (None, None)
        size: (100, 50)
        Button:
            text: 'Open'
            on_press: app.open_new()
